# Generated by Django 5.1 on 2024-08-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_remove_volunteeruser_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeruser',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
