# Generated by Django 5.1 on 2024-08-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_alter_volunteeruser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeruser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
